CREATE TABLE [dbo].[STUDENT_MASTER] (
    [ID]      INT         NOT NULL,
    [NAME]    NCHAR (10)  NULL,
    [ADDRESS] NCHAR (100) NULL,
    [DOB]     DATE        NULL,
    CONSTRAINT [ADB_CONT] PRIMARY KEY CLUSTERED ([ID] ASC)
);



